cubes:
  - name: application_themes
    data_source: fluid-replica
    sql: |-
      SELECT * FROM public.application_themes
      WHERE company_id = { COMPILE_CONTEXT.securityContext.company_id }

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at
      - name: company_id
        type: number
        sql: company_id
      - name: name
        type: string
        sql: name
      - name: description
        type: string
        sql: description
      - name: global_stylesheet
        type: string
        sql: global_stylesheet
      - name: status
        type: number
        sql: status
      - name: custom_stylesheet
        type: string
        sql: custom_stylesheet
      - name: variables
        type: string
        sql: variables
      - name: version
        type: string
        sql: version

    measures:
      - name: count
        type: count

    joins:
      - name: companies
        sql: "{CUBE}.company_id = {companies}.id"
        relationship: many_to_one
      - name: application_theme_templates
        sql: "{CUBE}.id = {application_theme_templates}.application_theme_id"
        relationship: one_to_many
