cubes:
  - name: display_settings
    data_source: fluid-replica
    sql: |-
      SELECT * FROM public.display_settings
      WHERE company_id = { COMPILE_CONTEXT.securityContext.company_id }

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at
      - name: company_id
        type: number
        sql: company_id
      - name: setting_type
        type: string
        sql: setting_type
      - name: value
        type: string
        sql: value
      - name: active
        type: boolean
        sql: active

    measures:
      - name: count
        type: count

    joins:
      - name: companies
        sql: "{CUBE}.company_id = {companies}.id"
        relationship: many_to_one
