cubes:
  - name: products
    data_source: fluid-replica
    sql: |-
      SELECT * FROM public.products
      WHERE company_id = { COMPILE_CONTEXT.securityContext.company_id }

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: company_id
        type: number
        sql: company_id
      - name: title
        type: string
        sql: title
      - name: description
        type: string
        sql: description
      - name: price
        type: number
        sql: price
      - name: shipping
        type: number
        sql: shipping
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at
      - name: image_url
        type: string
        sql: image_url
      - name: compressed_image_url
        type: string
        sql: compressed_image_url
      - name: external_url
        type: string
        sql: external_url
      - name: no_index
        type: boolean
        sql: no_index
      - name: image_path
        type: string
        sql: image_path
      - name: shopify_id
        type: string
        sql: shopify_id
      - name: shopify_handle
        type: string
        sql: shopify_handle
      - name: in_stock
        type: boolean
        sql: in_stock
      - name: vendor
        type: string
        sql: vendor
      - name: public
        type: boolean
        sql: public
      - name: commission
        type: number
        sql: commission
      - name: last_synced_at
        type: time
        sql: last_synced_at
      - name: category_id
        type: number
        sql: category_id
      - name: collection_id
        type: number
        sql: collection_id
      - name: affiliate_commission
        type: number
        sql: affiliate_commission
      - name: integration_id
        type: number
        sql: integration_id
      - name: external_id
        type: string
        sql: external_id
      - name: upc
        type: string
        sql: upc
      - name: hs_code
        type: string
        sql: hs_code
      - name: cv
        type: number
        sql: cv
      - name: product_type
        type: string
        sql: product_type
      - name: weight
        type: string
        sql: weight
      - name: size
        type: string
        sql: size
      - name: shipping_time
        type: string
        sql: shipping_time
      - name: tax
        type: number
        sql: tax
      - name: track_quantity
        type: boolean
        sql: track_quantity
      - name: keep_selling
        type: boolean
        sql: keep_selling
      - name: auto_redirect
        type: string
        sql: auto_redirect
      - name: feature_text
        type: string
        sql: feature_text
      - name: introduction
        type: string
        sql: introduction
      - name: theme
        type: number
        sql: theme
      - name: tax_category_id
        type: number
        sql: tax_category_id
      - name: option_attrs
        type: string
        sql: option_attrs
      - name: publish_to_retail_store
        type: boolean
        sql: publish_to_retail_store
      - name: publish_to_rep_store
        type: boolean
        sql: publish_to_rep_store
      - name: publish_to_share_tab
        type: boolean
        sql: publish_to_share_tab
      - name: priority
        type: number
        sql: priority
      - name: status
        type: number
        sql: status
      - name: discarded_at
        type: time
        sql: discarded_at
      - name: prompts_enabled
        type: boolean
        sql: prompts_enabled
      - name: application_theme_template_id
        type: number
        sql: application_theme_template_id
      - name: international_tax_type
        type: string
        sql: international_tax_type
      - name: external_integration_market_id
        type: string
        sql: external_integration_market_id
      - name: metadata
        type: string
        sql: metadata
      - name: bundle
        type: boolean
        sql: bundle
      - name: show_reviews
        type: boolean
        sql: show_reviews
      - name: sku
        type: string
        sql: sku
      - name: slug
        type: string
        sql: slug
      - name: track_inventory_on_bundle_items
        type: boolean
        sql: track_inventory_on_bundle_items

    measures:
      - name: count
        type: count
      - name: average_price
        type: avg
        sql: price * 100

    joins:
      - name: companies
        sql: "{CUBE}.company_id = {companies}.id"
        relationship: many_to_one


    pre_aggregations:
    # Pre-aggregation definitions go here.
    # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
