cubes:
  - name: product_options
    data_source: fluid-replica
    sql_table: public.product_options

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: product_id
        type: number
        sql: product_id
      - name: option_id
        type: number
        sql: option_id
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at

    measures:
      - name: count
        type: count

    joins:
      - name: products
        sql: "{CUBE}.product_id = {products}.id"
        relationship: many_to_one
      - name: options
        sql: "{CUBE}.option_id = {options}.id"
        relationship: many_to_one
