cubes:
  - name: product_collections
    data_source: fluid-replica
    sql_table: public.product_collections

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: product_id
        type: number
        sql: product_id
      - name: collection_id
        type: number
        sql: collection_id
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at

    measures:
      - name: count
        type: count

    joins:
      - name: products
        sql: "{CUBE}.product_id = {products}.id"
        relationship: many_to_one
      - name: collections
        sql: "{CUBE}.collection_id = {collections}.id"
        relationship: many_to_one
