cubes:
  - name: application_theme_templates
    data_source: fluid-replica
    sql_table: public.application_theme_templates

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at
      - name: name
        type: string
        sql: name
      - name: description
        type: string
        sql: description
      - name: template_data
        type: string
        sql: template_data
      - name: version
        type: string
        sql: version
      - name: active
        type: boolean
        sql: active
      - name: default
        type: boolean
        sql: default

    measures:
      - name: count
        type: count
