cubes:
  - name: products
    data_source: fluid-replica
    sql: |-
      SELECT * FROM public.products
      WHERE company_id = { COMPILE_CONTEXT.securityContext.company_id }

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at
      - name: company_id
        type: number
        sql: company_id
      - name: description
        type: string
        sql: title
      - name: price
        type: number
        sql: price
      - name: shipping
        type: number
        sql: shipping
      - name: sku
        type: string
        sql: sku
      - name: image_url
        type: string
        sql: image_url
      - name: slug
        type: string
        sql: slug
      - name: in_stock
        type: boolean
        sql: in_stock
      - name: public
        type: boolean
        sql: public
      - name: commission
        type: string
        sql: commission
      - name: external_id
        type: string
        sql: external_id
      - name: cv
        type: number
        sql: cv
      - name: product_type
        type: string
        sql: product_type
      - name: tax
        type: number
        sql: tax
      - name: track_quantity
        type: boolean
        sql: track_quantity
      - name: keep_selling
        type: boolean
        sql: keep_selling
      - name: status
        type: string
        sql: status
      - name: discarded_at
        type: time
        sql: discarded_at
      - name: bundle
        type: boolean
        sql: bundle
      - name: title
        type: string
        sql: title

    measures:
      - name: count
        type: count
      - name: average_price
        type: avg
        sql: price * 100

    joins:
      - name: companies
        sql: "{CUBE}.company_id = {companies}.id"
        relationship: many_to_one


    pre_aggregations:
    # Pre-aggregation definitions go here.
    # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
