cubes:
  - name: product_redirects
    data_source: fluid-replica
    sql_table: public.product_redirects

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: product_id
        type: number
        sql: product_id
      - name: from_path
        type: string
        sql: from_path
      - name: to_path
        type: string
        sql: to_path
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at

    measures:
      - name: count
        type: count

    joins:
      - name: products
        sql: "{CUBE}.product_id = {products}.id"
        relationship: many_to_one
