cubes:
  - name: product_bundles
    data_source: fluid-replica
    sql: |-
      SELECT * FROM public.product_bundles
      WHERE company_id = { COMPILE_CONTEXT.securityContext.company_id }

    dimensions:
      - name: id
        type: string
        sql: id
        primary_key: true
        public: true
      - name: name
        type: string
        sql: name
      - name: description
        type: string
        sql: description
      - name: company_id
        type: number
        sql: company_id
      - name: active
        type: boolean
        sql: active
      - name: created_at
        type: time
        sql: created_at
      - name: updated_at
        type: time
        sql: updated_at

    measures:
      - name: count
        type: count

    joins:
      - name: companies
        sql: "{CUBE}.company_id = {companies}.id"
        relationship: many_to_one
